### ISSUE TITLE
Not an issue, but an question

### ISSUE THREAD

**Issue by MusculusMus** [gihannagalindez/boostdiff_inference#3]
Hi,

I smoothly tried the demo data and got the output txt files, I have no idea how to plot the similar network in your [preprint ](https://www.biorxiv.org/content/10.1101/2022.09.26.509450v1.full). Can you give a hint on how to do this from the txt out put files?

![image](https://user-images.githubusercontent.com/37739300/193874006-9e12df2f-2c8f-4598-9f70-1439597a6196.png)

Shuai

**Comment by gihannagalindez** [comment]
Hi Shuai,

I added the functions that can be used to plot the networks this way :)

**Comment by MusculusMus** [comment]
Thanks for your update,

I run the new version, and got the error at the final step: name 'graphviz_layout' is not defined, so I changed to random_layout and then I got this network which is not a good network visualization. I opened  the link<https://networkx.org/documentation/stable/reference/generated/networkx.drawing.nx_agraph.graphviz_layout.html> in the .py  scripts and have no idea how to define it. Can you give some advice on it?

I guess typos in your README.md:

***@***.***

I changed it to following scripts:
df_dis = pp.filter_network(file_net_dis, file_diff_dis, n_top_targets=10, n_top_edges=50)
df_con = pp.filter_network(file_net_con, file_diff_con, n_top_targets=10, n_top_edges=50)


I am new to python and this is my first python program, and sorry for the silly questions.


***@***.***


Shuai

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by TimFaro** [comment]
I ran into the same issue, I found a solution here: https://stackoverflow.com/a/39603436
You have to import the function directly with `from networkx.drawing.nx_agraph import graphviz_layout`
In my case, this resulted in another error: `ImportError: requires pygraphviz http://pygraphviz.github.io/` which could easily be solved by installing the package (e.g. `conda install --channel conda-forge pygraphviz`)
